import QtQuick

import "icons.js" as Icons

// One bundled icon (outlines in icons.js, generated by shared/tools/gen_svg_icons.py) drawn in `color`;
// `hex` is its codepoint
Image {
    property string hex
    property color color: "black"

    source: Icons.url(hex, color)
    sourceSize.width: width
    sourceSize.height: height
    fillMode: Image.PreserveAspectFit
    smooth: true
}
