import QtQuick
import org.kde.kirigami as Kirigami

// Icon from contents/icons (generated by tools/gen_icons.py), drawn in `color`
Kirigami.Icon {
    property string hex

    source: hex ? Qt.resolvedUrl("../icons/" + hex + ".svg") : ""
    isMask: true
    roundToIconSize: false
}
