import QtQuick

import "code/icons.js" as Icons

// Bundled icon (outlines in code/icons.js, generated by tools/gen_icons.py) drawn in `color`
Image {
    property string hex
    property color color: "black"

    source: Icons.url(hex, color)
    sourceSize.width: width
    sourceSize.height: height
    fillMode: Image.PreserveAspectFit
    smooth: true
}
